baseurl = "/"
languageCode = "en-us"
title = "Probabilistic Visualization Collection"
# theme = "mediumish-gohugo-theme"
theme = "bootstrap"
publishDir = "./docs/"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "\\.R$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
[[menu.main]]
    name = "Visualizations"
    url = "/visualization/"


[taxonomies]
  category = "categories"
  coverage = "coverage"
  tag = "tags"


[params]
    description = "Supplemental to _A Probabilistic Grammar of Graphics_"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    # [params.logo]
    # url = "logo.png"
    # width = 50
    # height = 50
    # alt = "Logo"

    [params.index]
      # picture = "/images/author.jpg"
      title = "Probabilistic Visualization Collection"
      subtitle = "Supplemental to "
      mdtext = ""
      alertbar = true
